/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.logic.UsuarioLogic;
import sql.Metodos_sql;

/**
 *
 * @author jever
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }
    
    Metodos_sql metodos = new Metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLogin = new javax.swing.JPanel();
        jLTítulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        chkMostrarContraseña = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFondo = new javax.swing.JPanel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTítulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLTítulo.setForeground(new java.awt.Color(66, 108, 180));
        jLTítulo.setText("MedidaShoes");
        jPLogin.add(jLTítulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/zapatilla_inicio.png"))); // NOI18N
        jPLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Zapato_inicio.png"))); // NOI18N
        jPLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, 60, 50));

        jLabel3.setText("Contraseña:");
        jPLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, 20));

        jLabel4.setText("Usuario: ");
        jPLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 20));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));
        jPLogin.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, -1));

        chkMostrarContraseña.setText("Mostrar Contraseña");
        chkMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContraseñaActionPerformed(evt);
            }
        });
        jPLogin.add(chkMostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 30));

        btnRegistrar.setText("Regístrate");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPLogin.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 250, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿No tienes cuenta?");
        jPLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, -1));

        getContentPane().add(jPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 310, 360));

        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoZapatos.jpg"))); // NOI18N
        jFondo.add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContraseñaActionPerformed
        if(chkMostrarContraseña.isSelected()){
            txtContraseña.setEchoChar((char)0);
        }else{
            txtContraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_chkMostrarContraseñaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String busqueda_uRegistrado = metodos.buscarUsuarioRegistrado(txtUsuario.getText(), txtContraseña.getText());
        
        if(txtUsuario.getText().equals("root") && txtContraseña.getText().equals("123456")){
            JOptionPane.showMessageDialog(this,"Bienvenido, iniciaste como root (Administrador)");
            FrmTienda ventana = new FrmTienda();
            ventana.setVisible(true);
            ventana.lblNombre.setText("Administrador");
            this.dispose();
        }
        else if(busqueda_uRegistrado.equals("Usuario registrado")){
            String busqueda_usuario = metodos.buscarUsuario(txtUsuario.getText());
            JOptionPane.showMessageDialog(this, "Bienvenido(a) \n"+busqueda_usuario);
            
            FrmTienda ventana = new FrmTienda();
            ventana.setVisible(true);
            ventana.lblNombre.setText(busqueda_usuario);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"Usuario no registrado.");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        FrmRegistrarUsuario frmRegistrarUsuario = new FrmRegistrarUsuario(this, true);
        frmRegistrarUsuario.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkMostrarContraseña;
    public javax.swing.JPanel jFondo;
    public javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLTítulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
