package vistas;

import modelo.logic.CentrarTexto;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import sql.ConexionBaseDatos;
import sql.Metodos_sql;

public class FrmTienda extends javax.swing.JFrame {

    public TableCellRenderer centerAligh = new CentrarTexto();
    
    public FrmTienda() {
        initComponents();
        this.setLocationRelativeTo(null);
        /*
        this.jTable_MostrarTareas.setModel(modelo);
        this.modelo.addColumn("Género");
        this.modelo.addColumn("Talla");
        this.modelo.addColumn("Marca");
        this.modelo.addColumn("Cantidad");
        this.modelo.addColumn("Precio unitario");
        this.modelo.addColumn("Total a pagar");
        */
    }
    
    Metodos_sql metodos = new Metodos_sql();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPPrincipal = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPNombreUsuario = new javax.swing.JPanel();
        jPRealizarCompras = new javax.swing.JPanel();
        botonh = new javax.swing.JRadioButton();
        botonm = new javax.swing.JRadioButton();
        jLGénero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbotallas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btngenerar = new javax.swing.JButton();
        cbomarca = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPDetallesCompra = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MostrarTareas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnlimpiartabla = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnnetopagar = new javax.swing.JButton();
        txtnetopagar = new javax.swing.JTextField();
        btnquitar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFondoImagen = new javax.swing.JLabel();
        lblFondoImagen1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPPrincipal.setBackground(new java.awt.Color(252, 252, 244));
        jPPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 120, 26));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido: ");
        jPPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, 30));

        jPNombreUsuario.setBackground(new java.awt.Color(28, 245, 255));

        javax.swing.GroupLayout jPNombreUsuarioLayout = new javax.swing.GroupLayout(jPNombreUsuario);
        jPNombreUsuario.setLayout(jPNombreUsuarioLayout);
        jPNombreUsuarioLayout.setHorizontalGroup(
            jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPNombreUsuarioLayout.setVerticalGroup(
            jPNombreUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPPrincipal.add(jPNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 210, 30));

        jPRealizarCompras.setBackground(new java.awt.Color(164, 255, 247));
        jPRealizarCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Realizar Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPRealizarCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(botonh);
        botonh.setForeground(new java.awt.Color(252, 252, 244));
        botonh.setText("Hombre");
        botonh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(botonh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        buttonGroup1.add(botonm);
        botonm.setForeground(new java.awt.Color(252, 252, 244));
        botonm.setText("Mujer");
        jPRealizarCompras.add(botonm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLGénero.setForeground(new java.awt.Color(252, 252, 244));
        jLGénero.setText("Género:");
        jPRealizarCompras.add(jLGénero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(252, 252, 244));
        jLabel2.setText("Tallas:");
        jPRealizarCompras.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        cbotallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "36", "37", "38" , "39" , "40" , "41" , "42" , "43" , "44" , "45"}));
        cbotallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotallasActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(cbotallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 100, -1));

        jLabel3.setForeground(new java.awt.Color(252, 252, 244));
        jLabel3.setText("Marca:");
        jPRealizarCompras.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel4.setForeground(new java.awt.Color(252, 252, 244));
        jLabel4.setText("Cantidad:");
        jPRealizarCompras.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        jPRealizarCompras.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, -1));

        jLabel5.setForeground(new java.awt.Color(252, 252, 244));
        jLabel5.setText("Precio:");
        jPRealizarCompras.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 100, -1));

        jLabel6.setText("Total a pagar:");
        jPRealizarCompras.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, -1));

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 40));

        btngenerar.setText("Generar Compra");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(btngenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 160, 40));

        cbomarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Adidas", "Bata", "DC", "New Athletic", "North Star", "Puma", "Tigre", "Vans" }));
        cbomarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomarcaActionPerformed(evt);
            }
        });
        jPRealizarCompras.add(cbomarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 100, -1));

        jPanel2.setBackground(new java.awt.Color(66, 108, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPRealizarCompras.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 770, 70));

        jPPrincipal.add(jPRealizarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 820, 210));

        jPDetallesCompra.setBackground(new java.awt.Color(164, 255, 247));
        jPDetallesCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles de la compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPDetallesCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_MostrarTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_MostrarTareas);

        jPDetallesCompra.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1040, 190));

        jLabel7.setText("Neto a pagar:          S/.");
        jPDetallesCompra.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, -1, -1));

        btnlimpiartabla.setText("Limpiar Tabla");
        btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartablaActionPerformed(evt);
            }
        });
        jPDetallesCompra.add(btnlimpiartabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 40));

        btnCargar.setText("Cargar tabla");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPDetallesCompra.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 40));

        btnnetopagar.setText("Neto a Pagar:");
        jPDetallesCompra.add(btnnetopagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, 40));
        jPDetallesCompra.add(txtnetopagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 232, 80, 30));

        btnquitar1.setText("Quitar Compra");
        jPDetallesCompra.add(btnquitar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 40));

        jPPrincipal.add(jPDetallesCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1080, 280));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 230, 180));

        getContentPane().add(jPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1120, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Zapatos_Sistema.jpg"))); // NOI18N
        lblFondoImagen.setText("jLabel1");
        jPanel1.add(lblFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 1190, 650));

        lblFondoImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Zapatos_Sistema.jpg"))); // NOI18N
        lblFondoImagen1.setText("jLabel1");
        jPanel1.add(lblFondoImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1190, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 1230, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhActionPerformed
    DefaultTableModel modelo = new DefaultTableModel ();
    private void btnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiartablaActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
         if(txtcantidad.getText().length()>=2)
        {
            evt.consume();
            }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void cbomarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbomarcaActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        
        // Aquí agregar la operacioooooooooooooooon para sacar resultado y listo xd
        
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        String where;
        
        try {
            
            jTable_MostrarTareas.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionBaseDatos conn = new ConexionBaseDatos();
            Connection con = conn.conectar();

            TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(modelo);//iniciamos el sorter
            jTable_MostrarTareas.setRowSorter(sorter);//indicamos a la tabla el sorter

            String sql = "SELECT genero,talla,marca,cantidad,precio,totalPagar FROM compras ";
            System.out.println(sql);
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();//cantidad de datos

            //nombramos las columnas
            modelo.addColumn("Género");
            modelo.addColumn("Talla");
            modelo.addColumn("Marca");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Precio");
            modelo.addColumn("Total a Pagar");

            while (rs.next()) {//llenar cada fila
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);//llenamos filas
            }

            int [] anchos = {50, 300, 50, 50, 50, 50};

            for (int x = 0; x < cantidadColumnas; x++){ //Cambie cantidadColumnas -> 4
                jTable_MostrarTareas.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
        //Alinear al centro las columnas de fecha, hora y prioridad
        jTable_MostrarTareas.getColumnModel().getColumn(2).setCellRenderer(centerAligh);
        jTable_MostrarTareas.getColumnModel().getColumn(3).setCellRenderer(centerAligh);
        jTable_MostrarTareas.getColumnModel().getColumn(4).setCellRenderer(centerAligh);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        
        botonh.setActionCommand("Hombre");
        botonm.setActionCommand("Mujer");
        
        String sexoSelected = buttonGroup1.getSelection().getActionCommand();
        float precio = Float.valueOf(txtprecio.getText());
        float total = Float.valueOf(txttotal.getText());
        
        int a = metodos.guardarCompra( (sexoSelected), Integer.parseInt(cbotallas.getSelectedItem().toString()), 
                (cbomarca.getSelectedItem().toString()),Integer.parseInt(txtcantidad.getText()), precio, total);
        
        if (a > 0) {
                    JOptionPane.showMessageDialog(this, "Nueva compra añadida");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo añadir la compra");
                }
        
        String busqueda_usuario = lblNombre.getText();
        String busqueda_id = metodos.buscarId(busqueda_usuario);
    }//GEN-LAST:event_btngenerarActionPerformed

    private void cbotallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotallasActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        
    }//GEN-LAST:event_txtprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonh;
    private javax.swing.JRadioButton botonm;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiartabla;
    private javax.swing.JButton btnnetopagar;
    private javax.swing.JButton btnquitar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbomarca;
    public javax.swing.JComboBox<String> cbotallas;
    private javax.swing.JLabel jLGénero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPDetallesCompra;
    private javax.swing.JPanel jPNombreUsuario;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JPanel jPRealizarCompras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_MostrarTareas;
    private javax.swing.JLabel lblFondoImagen;
    private javax.swing.JLabel lblFondoImagen1;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnetopagar;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
